import { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  ArrowLeft,
  Map as MapIcon,
  Mic,
  Accessibility as EasierIcon,
  Droplets as ToiletIcon,
  Utensils as RestaurantIcon,
  Camera,
  MoreVertical,
  Plus,
  Minus,
  X,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  LocateFixed
} from 'lucide-react';
import BottomBar from '../UI/BottomBar';
import ItemDescription from '../UI/ItemDescription';
import QRScanner from '../UI/QRScanner';
import { createCollisionGrid, findPath } from '../../utils/gridPathfinding';
import { useSpeaker } from '../../utils/useSpeaker';
import './NavigatorApp.css';

// Sample JSON Data generated by the Editor / Backend
const mockMuseumData = {
  "museumCenter": [
    40.77943,
    -73.96324
  ],
  "layers": [
    {
      "id": 1,
      "name": "Layer 1"
    }
  ],
  "lines": [
    {
      "id": 1774260197998,
      "type": "poi-exhibit",
      "points": [
        {
          "lat": 40.778647003126665,
          "lng": -73.965132671673,
          "x": -5645.1131511330605,
          "y": 3084.0915300250053
        },
        {
          "lat": 40.77906142250546,
          "lng": -73.96486453446234,
          "x": -4845.36276870966,
          "y": 1451.7686004638672
        },
        {
          "lat": 40.77900454156733,
          "lng": -73.9645749462748,
          "x": -3981.6323556900024,
          "y": 1675.8129240870476
        },
        {
          "lat": 40.779516468257015,
          "lng": -73.96423173064517,
          "x": -2957.9518663287163,
          "y": -340.5859887599945
        },
        {
          "lat": 40.7795896003192,
          "lng": -73.96442478943683,
          "x": -3533.7721415162086,
          "y": -628.6429764032364
        },
        {
          "lat": 40.779857750525004,
          "lng": -73.96458567176323,
          "x": -4013.622371017933,
          "y": -1684.8519307971
        },
        {
          "lat": 40.7799471336864,
          "lng": -73.96395286794605,
          "x": -2126.2114685177803,
          "y": -2036.9215822815895
        },
        {
          "lat": 40.78041842473008,
          "lng": -73.96359892682798,
          "x": -1070.5409638285637,
          "y": -3893.2888354063034
        },
        {
          "lat": 40.780515932804434,
          "lng": -73.96383488757336,
          "x": -1774.3213002681732,
          "y": -4277.364818930626
        },
        {
          "lat": 40.78094659175376,
          "lng": -73.963523848409,
          "x": -846.6108567118645,
          "y": -5973.700412273407
        },
        {
          "lat": 40.78067032029599,
          "lng": -73.96290177008025,
          "x": 1008.8100304603577,
          "y": -4885.485125899315
        },
        {
          "lat": 40.78080845616851,
          "lng": -73.9628052406844,
          "x": 1296.7201681733131,
          "y": -5429.592769086361
        },
        {
          "lat": 40.78024778525561,
          "lng": -73.96170051537646,
          "x": 4591.691743552685,
          "y": -3221.155864417553
        },
        {
          "lat": 40.77977649300118,
          "lng": -73.96205445649453,
          "x": 3536.021238863468,
          "y": -1364.7886111736298
        },
        {
          "lat": 40.77782628260922,
          "lng": -73.96344876999001,
          "x": -622.6807496547699,
          "y": 6316.731057167053
        },
        {
          "lat": 40.77858199593069,
          "lng": -73.96511122069616,
          "x": -5581.133120596409,
          "y": 3340.142185628414
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774260221497,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.780191861821976,
          "lng": -73.96377512408382,
          "x": -1596.06974953413,
          "y": -3000.8790521025658
        },
        {
          "lat": 40.779582431035855,
          "lng": -73.9621984772851,
          "x": 3106.462498962879,
          "y": -600.4041557312012
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774260229598,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.77934290131403,
          "lng": -73.96433571330012,
          "x": -3268.0922151207924,
          "y": 343.0687093734741
        },
        {
          "lat": 40.77998483723315,
          "lng": -73.96392278199568,
          "x": -2036.4766262173653,
          "y": -2185.4315147399902
        }
      ],
      "layerId": 1
    }
  ],
  "pois": [
    {
      "id": 1774260201080,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.78078706675734,
        "lng": -73.96346944096841,
        "x": -684.3343442082405,
        "y": -5345.341284573078
      },
      "layerId": 1
    },
    {
      "id": 1774260201765,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.78073425011713,
        "lng": -73.9631852155251,
        "x": 163.40106111764908,
        "y": -5137.30012691021
      },
      "layerId": 1
    },
    {
      "id": 1774260202947,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.780447820682895,
        "lng": -73.96243979407943,
        "x": 2386.707124233246,
        "y": -4009.0769255161285
      },
      "layerId": 1
    },
    {
      "id": 1774260203975,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.779495078429804,
        "lng": -73.9624585636842,
        "x": 2330.7245973944664,
        "y": -256.33450424671173
      },
      "layerId": 1
    },
    {
      "id": 1774260205050,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77874953285046,
        "lng": -73.96305114691977,
        "x": 563.2762523293495,
        "y": 2680.246452331543
      },
      "layerId": 1
    },
    {
      "id": 1774260207114,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.778261978484494,
        "lng": -73.96333806043044,
        "x": -292.4766262769699,
        "y": 4600.624786436558
      },
      "layerId": 1
    },
    {
      "id": 1774260207941,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77835745824162,
        "lng": -73.96435698183096,
        "x": -3331.528079330921,
        "y": 4224.550386071205
      },
      "layerId": 1
    },
    {
      "id": 1774260208794,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77891814511014,
        "lng": -73.96445887397104,
        "x": -3635.433224737644,
        "y": 2016.1134814023972
      },
      "layerId": 1
    },
    {
      "id": 1774260211777,
      "type": "exhibit",
      "subType": null,
      "name": "Rosetta Stone",
      "position": {
        "lat": 40.779783543813394,
        "lng": -73.96440792790101,
        "x": -3483.4806520342827,
        "y": -1392.5608714818954
      },
      "layerId": 1
    },
    {
      "id": 1774260233390,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77969027879997,
        "lng": -73.96409707118262,
        "x": -2556.3143748044968,
        "y": -1025.2019815444946
      },
      "layerId": 1
    },
    {
      "id": 1774260234511,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77988326550721,
        "lng": -73.9629655321536,
        "x": 818.6322389245033,
        "y": -1785.3523654937744
      },
      "layerId": 1
    },
    {
      "id": 1774260236512,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.777987908611564,
        "lng": -73.96384234083249,
        "x": -1796.5515115261078,
        "y": 5680.124562323093
      },
      "layerId": 1
    },
    {
      "id": 1774260247175,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "position": {
        "lat": 40.778530143293246,
        "lng": -73.96391456045481,
        "x": -2011.9549254179,
        "y": 3544.379423379898
      },
      "layerId": 1
    },
    {
      "id": 1774260247609,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "position": {
        "lat": 40.778924248750194,
        "lng": -73.96401913396699,
        "x": -2323.8575745821,
        "y": 1992.0723236203194
      },
      "layerId": 1
    },
    {
      "id": 1774260249008,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "position": {
        "lat": 40.779103017464934,
        "lng": -73.96271598712315,
        "x": 1562.9292838573456,
        "y": 1287.9330207109451
      },
      "layerId": 1
    },
    {
      "id": 1774260250368,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "position": {
        "lat": 40.78026500238393,
        "lng": -73.963616928151,
        "x": -1124.2320010066032,
        "y": -3288.972448348999
      },
      "layerId": 1
    }
  ]
}

// Autoscale the arbitrary x/y coordinates into the 500x500 canvas preserving aspect ratio
const transformDataForCanvas = (data, canvasSize = 500, padding = 40) => {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  data.lines.forEach(line => line.points.forEach(pt => {
    if (pt.x < minX) minX = pt.x; if (pt.x > maxX) maxX = pt.x;
    if (pt.y < minY) minY = pt.y; if (pt.y > maxY) maxY = pt.y;
  }));
  data.pois.forEach(poi => {
    if (poi.position.x < minX) minX = poi.position.x; if (poi.position.x > maxX) maxX = poi.position.x;
    if (poi.position.y < minY) minY = poi.position.y; if (poi.position.y > maxY) maxY = poi.position.y;
  });

  if (minX === Infinity) return { scale: 1, offsetX: 0, offsetY: 0 };

  const width = Math.max(maxX - minX, 1);
  const height = Math.max(maxY - minY, 1);
  const drawArea = canvasSize - padding * 2;
  const scale = drawArea / Math.max(width, height);
  const offsetX = (canvasSize - (width * scale)) / 2 - minX * scale;
  const offsetY = (canvasSize - (height * scale)) / 2 - minY * scale;

  return { scale, offsetX, offsetY };
};

const { scale, offsetX, offsetY } = transformDataForCanvas(mockMuseumData);
const tx = (x) => x * scale + offsetX;
const ty = (y) => y * scale + offsetY;

const mockTourItems = mockMuseumData.pois
  .filter(poi => poi.type === 'exhibit')
  .map(poi => ({
    id: poi.id,
    name: poi.name,
    //TODO : add images
    desc: `You are currently navigating toward the famous ${poi.name}. This is one of the museum's most prized exhibits. Bring yourself closer to discover its history and secrets.`,
    x: tx(poi.position.x),
    y: ty(poi.position.y)
  }));

export default function NavigatorApp() {
  const { state } = useLocation();
  const navigate = useNavigate();
  const canvasRef = useRef(null);
  const { speak, pause, stop, seek, isSpeaking, currentTime, duration } = useSpeaker();

  const [items] = useState(mockTourItems);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [showDescription, setShowDescription] = useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const [showMoreMenu, setShowMoreMenu] = useState(false);
  const [isCameraActive, setIsCameraActive] = useState(false);
  const [aiResponse, setAiResponse] = useState(null);
  const [hasTriggeredCurrent, setHasTriggeredCurrent] = useState(false);

  // Pathfinding and Navigation States
  const [collisionGrid, setCollisionGrid] = useState(null);
  const [currentPath, setCurrentPath] = useState([]);
  const [mapZoom, setMapZoom] = useState(4.5); // Default significantly zoomed in for human-to-museum scale
  const moveIntervalRef = useRef(null);

  // Native Full-Screen Scale
  const [windowSize, setWindowSize] = useState({ w: window.innerWidth, h: window.innerHeight });

  useEffect(() => {
    const handleResize = () => setWindowSize({ w: window.innerWidth, h: window.innerHeight });
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Camera and Panning state
  const [isTrackingUser, setIsTrackingUser] = useState(true);
  const [cameraPos, setCameraPos] = useState({ x: 250, y: 250 });
  const [isPanning, setIsPanning] = useState(false);
  const lastPanRef = useRef({ x: 0, y: 0 });

  // User simulated position (started near the first exhibit)
  const startPos = items.length > 0 ? { x: items[0].x, y: items[0].y + 40 } : { x: 250, y: 250 };
  const [userPos, setUserPos] = useState(startPos);

  const currentItem = items[currentIndex];

  useEffect(() => {
    setCollisionGrid(createCollisionGrid(mockMuseumData.lines, mockMuseumData.pois, tx, ty));
  }, []);

  useEffect(() => {
    if (collisionGrid && currentItem) {
      setCurrentPath(findPath(collisionGrid, userPos, { x: currentItem.x, y: currentItem.y }));
    }
  }, [userPos, currentItem, collisionGrid]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');

    // Clear background
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.save(); // Save default context state
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';

    // Camera Transform System
    const cameraX = isTrackingUser ? userPos.x : cameraPos.x;
    const cameraY = isTrackingUser ? userPos.y : cameraPos.y;

    if (mapZoom > 1) {
      // 1. Move origin to canvas center
      ctx.translate(canvas.width / 2, canvas.height / 2);
      // 2. Scale up
      ctx.scale(mapZoom, mapZoom);
      // 3. Move origin back, offset by Camera Pos
      ctx.translate(-cameraX, -cameraY);
    }

    // Draw high-end grid background
    const gridSize = 100;
    ctx.beginPath();
    ctx.strokeStyle = '#f1f5f9';
    ctx.lineWidth = 1 / mapZoom;
    for (let x = -2000; x <= 4000; x += gridSize) {
      ctx.moveTo(x, -8000); ctx.lineTo(x, 2000);
    }
    for (let y = -8000; y <= 2000; y += gridSize) {
      ctx.moveTo(-2000, y); ctx.lineTo(4000, y);
    }
    ctx.stroke();

    // Draw Floor Fill based on external walls
    mockMuseumData.lines.filter(l => l.type === 'ext-wall').forEach(line => {
      ctx.beginPath();
      line.points.forEach((pt, i) => {
        const cx = tx(pt.x);
        const cy = ty(pt.y);
        if (i === 0) ctx.moveTo(cx, cy); else ctx.lineTo(cx, cy);
      });
      ctx.fillStyle = '#ffffff';
      ctx.fill();
    });

    // Draw lines (walls) from JSON
    mockMuseumData.lines.forEach(line => {
      ctx.beginPath();
      line.points.forEach((pt, i) => {
        const cx = tx(pt.x);
        const cy = ty(pt.y);
        if (i === 0) ctx.moveTo(cx, cy);
        else ctx.lineTo(cx, cy);
      });

      const isExt = line.type === 'ext-wall';
      ctx.strokeStyle = isExt ? '#1e293b' : '#94a3b8';
      ctx.lineWidth = isExt ? 8 / (mapZoom * 0.7) : 3 / (mapZoom * 0.7);

      if (isExt) {
        ctx.shadowColor = 'rgba(0,0,0,0.1)';
        ctx.shadowBlur = 10 / (mapZoom * 0.7);
      }
      ctx.stroke();
      ctx.shadowBlur = 0; // Reset shadow
    });

    // Draw POIs (Non-exhibits) from JSON
    mockMuseumData.pois.forEach(poi => {
      if (poi.type === 'exhibit') return; // Handled below in tour items

      const cx = tx(poi.position.x);
      const cy = ty(poi.position.y);

      // Match Editor.jsx HTML box styling exactly
      let label = 'EX';
      let bgColor = '#8b5cf6'; // exhibit

      if (poi.type === 'exit') {
        label = poi.subType === 'emergency' ? 'SOS' : 'Exit';
        bgColor = poi.subType === 'emergency' ? '#ef4444' : '#10b981';
      } else if (poi.type === 'restaurant') {
        label = poi.subType === 'bar' ? 'Bar' : poi.subType === 'restaurant-bar' ? 'R&B' : 'Café';
        bgColor = '#f59e0b';
      } else if (poi.type === 'restroom') {
        label = 'WC';
        bgColor = '#0ea5e9';
      }

      ctx.save();
      ctx.shadowColor = 'rgba(0,0,0,0.2)';
      ctx.shadowBlur = 8 / mapZoom;
      ctx.fillStyle = bgColor;
      const boxW = 38 / (mapZoom * 0.8);
      const boxH = 22 / (mapZoom * 0.8);
      ctx.beginPath();
      ctx.roundRect(cx - boxW / 2, cy - boxH / 2, boxW, boxH, 6 / (mapZoom * 0.8));
      ctx.fill();
      ctx.restore();

      ctx.fillStyle = 'white';
      ctx.font = `bold ${10 / (mapZoom * 0.8)}px sans-serif`;
      ctx.textBaseline = 'middle';
      ctx.textAlign = 'center';
      ctx.fillText(label.toUpperCase(), cx, cy);
    });

    // Draw current routing path
    if (currentPath.length > 0) {
      ctx.beginPath();
      ctx.moveTo(userPos.x, userPos.y);
      currentPath.forEach((pt) => ctx.lineTo(pt.x, pt.y));
      ctx.strokeStyle = '#3b82f6';
      ctx.lineWidth = 5 / (mapZoom * 0.7);
      ctx.setLineDash([12 / (mapZoom * 0.7), 8 / (mapZoom * 0.7)]);
      ctx.globalAlpha = 0.5;
      ctx.stroke();
      ctx.globalAlpha = 1.0;
      ctx.setLineDash([]);
    }

    // Draw active Tour Items (Exhibits)
    items.forEach((item, index) => {
      const isActive = index === currentIndex;
      ctx.beginPath();
      ctx.arc(item.x, item.y, 10 / (mapZoom * 0.8), 0, 2 * Math.PI);

      const grad = ctx.createRadialGradient(item.x, item.y, 0, item.x, item.y, 10 / (mapZoom * 0.8));
      grad.addColorStop(0, isActive ? '#f87171' : '#cbd5e1');
      grad.addColorStop(1, isActive ? '#ef4444' : '#94a3b8');

      ctx.fillStyle = grad;
      ctx.fill();

      if (isActive) {
        ctx.beginPath();
        ctx.arc(item.x, item.y, 18 / (mapZoom * 0.8), 0, 2 * Math.PI);
        ctx.strokeStyle = 'rgba(239, 68, 68, 0.3)';
        ctx.lineWidth = 4 / (mapZoom * 0.8);
        ctx.stroke();
      }
    });

    // Draw User Location
    ctx.save();
    ctx.shadowColor = 'rgba(59, 130, 246, 0.5)';
    ctx.shadowBlur = 15 / mapZoom;

    // Outer pulse ring
    ctx.beginPath();
    ctx.arc(userPos.x, userPos.y, 14 / (mapZoom * 0.8), 0, 2 * Math.PI);
    ctx.fillStyle = 'rgba(59, 130, 246, 0.2)';
    ctx.fill();

    // Inner core
    ctx.beginPath();
    ctx.arc(userPos.x, userPos.y, 9 / (mapZoom * 0.8), 0, 2 * Math.PI);
    ctx.fillStyle = '#3b82f6';
    ctx.fill();
    ctx.strokeStyle = '#fff';
    ctx.lineWidth = 2.5 / (mapZoom * 0.8);
    ctx.stroke();
    ctx.restore();

    ctx.restore(); // Undo camera transforms

  }, [currentIndex, items, userPos, cameraPos, mapZoom, isTrackingUser, windowSize]);

  // Proximity Auto-Trigger Pop-up
  useEffect(() => {
    if (currentItem && !hasTriggeredCurrent) {
      const dx = userPos.x - currentItem.x;
      const dy = userPos.y - currentItem.y;
      const distance = Math.sqrt(dx * dx + dy * dy);
      if (distance < 20) {
        // Fire the ItemDescription component overlay Pop-Up
        setShowPopup(true);
        setHasTriggeredCurrent(true);
      }
    }
  }, [userPos, currentItem, hasTriggeredCurrent]);

  // Reset auto-trigger when moving to next item
  useEffect(() => {
    setHasTriggeredCurrent(false);
    setShowPopup(false); // Hide popup (proximity-based, independent from bottom bar)
  }, [currentIndex]);

  // Synchronize audio playback with isPlaying state
  useEffect(() => {
    if (isPlaying && currentItem) {
      speak(currentItem.desc, currentItem.id);
    } else {
      pause();
    }
  }, [isPlaying, currentItem, speak, pause]);

  // Sync internal UI isPlaying with actual audio playback state
  useEffect(() => {
    // Allows the Play button to reset when the audio stops naturally
    setIsPlaying(isSpeaking);
  }, [isSpeaking]);

  // Controller Logic
  const moveUser = (dx, dy) => {
    setUserPos(prev => {
      const step = 4;
      // Convert abstract direction to dynamic relative size (optional: could stay static 4px)
      const nx = prev.x + dx * step;
      const ny = prev.y + dy * step;


      if (!collisionGrid) return prev;

      const c = Math.floor(nx / collisionGrid.gridSize);
      const r = Math.floor(ny / collisionGrid.gridSize);

      if (c >= 0 && c < collisionGrid.cols && r >= 0 && r < collisionGrid.rows && collisionGrid.grid[r][c] === 0) {
        return { x: nx, y: ny };
      }
      return prev;
    });
  };

  const startMove = (dx, dy) => {
    if (moveIntervalRef.current) clearInterval(moveIntervalRef.current);
    setIsPlaying(false);
    setIsTrackingUser(true); // Snap camera back to user when moving!
    moveUser(dx, dy);
    moveIntervalRef.current = setInterval(() => moveUser(dx, dy), 50);
  };

  const stopMove = () => {
    if (moveIntervalRef.current) {
      clearInterval(moveIntervalRef.current);
      moveIntervalRef.current = null;
    }
  };

  // Canvas Panning Controls
  const handlePointerDown = (e) => {
    e.preventDefault();
    setIsPanning(true);
    // Unbind camera from user dot on touch layout
    if (isTrackingUser) {
      setIsTrackingUser(false);
      setCameraPos(userPos);
    }
    lastPanRef.current = { x: e.clientX, y: e.clientY };
  };

  const handlePointerMove = (e) => {
    if (!isPanning) return;
    const dx = e.clientX - lastPanRef.current.x;
    const dy = e.clientY - lastPanRef.current.y;
    lastPanRef.current = { x: e.clientX, y: e.clientY };

    // Move camera relative to zoom factor
    // Loosen clamps to allow freer exploration of the large map
    setCameraPos(prev => ({
      x: prev.x - dx / mapZoom,
      y: prev.y - dy / mapZoom
    }));
  };

  const handlePointerUp = () => {
    setIsPanning(false);
  };

  const handleNext = () => {
    if (currentIndex < items.length - 1) {
      setCurrentIndex(prev => prev + 1);
      setIsPlaying(false);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex(prev => prev - 1);
      setIsPlaying(false);
    }
  };

  const togglePlay = () => {
    setIsPlaying(!isPlaying);
  };

  const handleMicRequest = async () => {
    try {
      // simulate recording and request
      setAiResponse("Listening...");
      const response = await fetch(`/api/AI/musem/${state?.visitId || 'default'}`);
      const data = await response.json();
      setAiResponse(data.message || "Something went wrong.");
    } catch (error) {
      console.error("AI Mic request failed.", error);
      setAiResponse("AI not available currently.");
    }
  };

  const handleCameraScan = () => {
    setIsCameraActive(true);
  };

  return (
    <div className="navigator-container">
      <div className="navigator-header">
        <button className="back-btn" onClick={() => navigate(-1)}>
          <ArrowLeft size={24} />
        </button>
        <h2>{state?.museum || 'Museum Tour'}</h2>
        <div style={{ width: 24 }}></div> {/* spacer */}
      </div>

      <div className="map-view-area">
        <div className="map-instructions">
          Target: <strong>{currentItem.name}</strong>
        </div>

        {/* New utility buttons */}
        <div className="utility-buttons-top">
          <div className="zoom-controls">
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.min(prev + 0.5, 4))} title="Zoom In"><Plus size={20} /></button>
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.max(prev - 0.5, 1))} title="Zoom Out"><Minus size={20} /></button>
          </div>

          <button
            className={`util-btn ${isCameraActive ? 'active' : ''}`}
            onClick={handleCameraScan}
            title="Scan QR Code"
          >
            <Camera size={24} />
          </button>

          <div className="more-menu-wrapper">
            <button
              className="util-btn"
              onClick={() => setShowMoreMenu(!showMoreMenu)}
              title="More Options"
            >
              {showMoreMenu ? <X size={24} /> : <MoreVertical size={24} />}
            </button>

            {showMoreMenu && (
              <div className="more-menu slide-in-top">
                <button className="menu-item" title="Find Toliet">
                  <ToiletIcon size={20} /> Toilet
                </button>
                <button className="menu-item" title="Find Restaurant">
                  <RestaurantIcon size={20} /> Restaurant
                </button>
              </div>
            )}
          </div>
        </div>

        {aiResponse && (
          <div className="ai-feedback fade-in">
            <span>{aiResponse}</span>
            <button onClick={() => setAiResponse(null)}><X size={14} /></button>
          </div>
        )}

        <canvas
          ref={canvasRef}
          width={windowSize.w}
          height={windowSize.h}
          className="indoor-canvas"
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerLeave={handlePointerUp}
        />

        {isCameraActive && (
          <QRScanner
            onScanSuccess={(decodedText) => {
              setIsCameraActive(false);
              alert(`QR Scan result: ${decodedText}`);
            }}
            onScanError={(err) => {
              console.error("QR Scan failed.", err);
              setIsCameraActive(false);
              alert("Camera unavailable or scan failed.");
            }}
            onClose={() => setIsCameraActive(false)}
          />
        )}

        {/* New utility buttons */}
        <div className="utility-buttons-top">
          {!isTrackingUser && (
            <button
              className="util-btn recenter-btn slide-in-top"
              onClick={() => setIsTrackingUser(true)}
              title="Recenter Camera"
            >
              <LocateFixed size={24} color="#3b82f6" />
            </button>
          )}

          <div className="zoom-controls">
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.min(prev + 0.5, 6))} title="Zoom In"><Plus size={20} /></button>
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.max(prev - 0.5, 1))} title="Zoom Out"><Minus size={20} /></button>
          </div>

          <button
            className={`util-btn ${isCameraActive ? 'active' : ''}`}
            onClick={handleCameraScan}
            title="Scan QR Code"
          >
            <Camera size={24} />
          </button>

          <div className="more-menu-wrapper">
            <button
              className="util-btn"
              onClick={() => setShowMoreMenu(!showMoreMenu)}
              title="More Options"
            >
              {showMoreMenu ? <X size={24} /> : <MoreVertical size={24} />}
            </button>

            {showMoreMenu && (
              <div className="more-menu slide-in-top">
                <button className="menu-item" title="Find Toliet">
                  <ToiletIcon size={20} /> Toilet
                </button>
                <button className="menu-item" title="Find Restaurant">
                  <RestaurantIcon size={20} /> Restaurant
                </button>
              </div>
            )}
          </div>
        </div>

        {/* D-Pad Controller for manual touring */}
        <div className="dpad-controller">
          <div className="dpad-row">
            <button onPointerDown={() => startMove(0, -1)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn up"><ChevronUp size={28} /></button>
          </div>
          <div className="dpad-row middle">
            <button onPointerDown={() => startMove(-1, 0)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn left"><ChevronLeft size={28} /></button>
            <div className="dpad-center"></div>
            <button onPointerDown={() => startMove(1, 0)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn right"><ChevronRight size={28} /></button>
          </div>
          <div className="dpad-row">
            <button onPointerDown={() => startMove(0, 1)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn down"><ChevronDown size={28} /></button>
          </div>
        </div>
      </div>

      {showPopup && (
        <ItemDescription
          item={currentItem}
          onPlayPause={togglePlay}
          isPlaying={isPlaying}
          onClose={() => setShowPopup(false)}
          currentTime={currentTime}
          duration={duration}
          onSeek={seek}
        />
      )}

      <BottomBar
        onPrev={handlePrev}
        onNext={handleNext}
        onPlayPause={togglePlay}
        onMic={handleMicRequest}
        onEasier={() => alert("Finding easier route...")}
        isPlaying={isPlaying}
        hasPrev={currentIndex > 0}
        hasNext={currentIndex < items.length - 1}
        progress={((currentIndex + 1) / items.length) * 100}
        showDescription={showDescription}
        setShowDescription={setShowDescription}
        currentItem={currentItem}
      />
    </div>
  );
}
