import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  ArrowLeft,
  Map as MapIcon,
  Mic,
  Accessibility as EasierIcon,
  Accessibility,
  Droplets as ToiletIcon,
  Utensils as RestaurantIcon,
  MoreVertical,
  Plus,
  Minus,
  X,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  LocateFixed,
  Sparkles,
  Radio,
  Users,
  Award
} from 'lucide-react';
import BottomBar from '../UI/BottomBar';
import ItemDescription from '../UI/ItemDescription';
import VoiceControlModal from '../UI/VoiceControlModal';
import AccessibilityModal from '../UI/AccessibilityModal';
import SyncSessionModal from '../UI/SyncSessionModal';
import QuizModal from '../UI/QuizModal';
import { useSpeaker } from '../../utils/useSpeaker';
import { useSpeechRecognition } from '../../utils/useSpeechRecognition';
import { createCollisionGrid, findPath } from '../../utils/gridPathfinding';
import { io } from 'socket.io-client';
import L from 'leaflet';
import './NavigatorApp.css';

// Sample JSON Data generated by the Editor / Backend
export const fetchMuseumData = async () => {
  try {
    const response = await fetch('/api/v1/navigator/museums/museumData');
    if (!response.ok) throw new Error('API request failed');
    const data = await response.json();
    // Check if data is valid and has exhibits, otherwise fallback to mock
    if (data && data.layers && data.pois && data.pois.some(p => p.type === 'exhibit')) {
      return data;
    }
    return mockMuseumData;
  } catch (error) {
    console.warn("Museum API data error, falling back to mock:", error);
    return mockMuseumData;
  }
};

const mockMuseumData = {
  "museumCenter": [
    40.77943,
    -73.96324
  ],
  "layers": [
    {
      "id": 1,
      "name": "Layer 1"
    },
    {
      "id": 2,
      "name": "Layer 2"
    }
  ],
  "lines": [
    {
      "id": 1774434372651,
      "type": "ext-wall",
      "points": [
        {
          "lat": 40.780488625473765,
          "lng": -73.96383672952653,
          "x": -1779.8151395916939,
          "y": -4169.803516983986
        },
        {
          "lat": 40.78091107539075,
          "lng": -73.96353900432588,
          "x": -891.8151395916939,
          "y": -5833.803516983986
        },
        {
          "lat": 40.78066329259213,
          "lng": -73.96292209625246,
          "x": 948.1848604083061,
          "y": -4857.803516983986
        },
        {
          "lat": 40.78076281202397,
          "lng": -73.96285235881807,
          "x": 1156.1848604083061,
          "y": -5249.803517043591
        },
        {
          "lat": 40.780267244396285,
          "lng": -73.96169096231462,
          "x": 4620.184860408306,
          "y": -3297.803516983986
        },
        {
          "lat": 40.77975339373045,
          "lng": -73.9620476961136,
          "x": 3556.184860408306,
          "y": -1273.803516983986
        },
        {
          "lat": 40.77981432484719,
          "lng": -73.9621737599373,
          "x": 3180.184860408306,
          "y": -1513.8035170435905
        },
        {
          "lat": 40.77935327800874,
          "lng": -73.96250903606416,
          "x": 2180.184860408306,
          "y": 302.1964830160141
        },
        {
          "lat": 40.77931875014314,
          "lng": -73.96240979433061,
          "x": 2476.184860408306,
          "y": 438.1964830160141
        },
        {
          "lat": 40.778810985341146,
          "lng": -73.96272897720338,
          "x": 1524.1848604083061,
          "y": 2438.1964829564095
        },
        {
          "lat": 40.778869886257176,
          "lng": -73.96286576986314,
          "x": 1116.1848604083061,
          "y": 2206.196483016014
        },
        {
          "lat": 40.778406801784314,
          "lng": -73.96319836378099,
          "x": 124.18486040830612,
          "y": 4030.1964830756187
        },
        {
          "lat": 40.778358055862554,
          "lng": -73.96306961774827,
          "x": 508.1848604083061,
          "y": 4222.196483016014
        },
        {
          "lat": 40.77795386954986,
          "lng": -73.963380753994,
          "x": -419.8151395916939,
          "y": 5814.196483075619
        },
        {
          "lat": 40.77868912121111,
          "lng": -73.96513760089876,
          "x": -5659.815139591694,
          "y": 2918.196483016014
        },
        {
          "lat": 40.77910548939905,
          "lng": -73.96484524011613,
          "x": -4787.815139591694,
          "y": 1278.196483016014
        },
        {
          "lat": 40.779018153849094,
          "lng": -73.96460652351381,
          "x": -4075.815139591694,
          "y": 1622.196483016014
        },
        {
          "lat": 40.77947310987365,
          "lng": -73.96427661180498,
          "x": -3091.815139591694,
          "y": -169.80351704359055
        },
        {
          "lat": 40.77968636943749,
          "lng": -73.96471112966539,
          "x": -4387.815139591694,
          "y": -1009.8035169839859
        },
        {
          "lat": 40.78010882445675,
          "lng": -73.96436244249345,
          "x": -3347.815139591694,
          "y": -2673.803516983986
        },
        {
          "lat": 40.77993618691294,
          "lng": -73.96393328905107,
          "x": -2067.815139591694,
          "y": -1993.803516983986
        },
        {
          "lat": 40.78039316766847,
          "lng": -73.96358728408815,
          "x": -1035.8151395916939,
          "y": -3793.8035170435905
        },
        {
          "lat": 40.7804845634423,
          "lng": -73.9638313651085,
          "x": -1763.8151395916939,
          "y": -4153.803517043591
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434496453,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.78039113664984,
          "lng": -73.96358460187913,
          "x": -1027.8151395916939,
          "y": -3785.803516983986
        },
        {
          "lat": 40.77981026277447,
          "lng": -73.9621737599373,
          "x": 3180.184860408306,
          "y": -1497.803516983986
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434502698,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.780133196779744,
          "lng": -73.96292209625246,
          "x": 948.1848604083061,
          "y": -2769.803516983986
        },
        {
          "lat": 40.78062470338458,
          "lng": -73.96257609128953,
          "x": 1980.1848604083061,
          "y": -4705.803516983986
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434512107,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.77825650174396,
          "lng": -73.96409958601,
          "x": -2563.815139591694,
          "y": 4622.196482956409
        },
        {
          "lat": 40.78001742816591,
          "lng": -73.96270215511323,
          "x": 1604.1848604083061,
          "y": -2313.8035169243813
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774466886305,
      "type": "int-wall",
      "points": [
        {
          "lat": 40.77993618691294,
          "lng": -73.96392256021501,
          "x": -2035.8151395916939,
          "y": -1993.803516983986
        },
        {
          "lat": 40.77947717196697,
          "lng": -73.96427661180498,
          "x": -3091.815139591694,
          "y": -185.8035169839859
        }
      ],
      "layerId": 2
    }
  ],
  "areas": [
    {
      "id": 1774434384242,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "points": [
        {
          "lat": 40.78038301257471,
          "lng": -73.96357387304307,
          "x": -995.8151395916939,
          "y": -3753.803516983986
        },
        {
          "lat": 40.779930093814976,
          "lng": -73.96392524242403,
          "x": -2043.8151395916939,
          "y": -1969.803516983986
        },
        {
          "lat": 40.779786384990295,
          "lng": -73.96360217570137
        },
        {
          "lat": 40.780239304729896,
          "lng": -73.96325080632042
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434400218,
      "type": "restaurant",
      "subType": "bar",
      "name": null,
      "points": [
        {
          "lat": 40.779456861497856,
          "lng": -73.96427661180498,
          "x": -3091.815139591694,
          "y": -105.8035169839859
        },
        {
          "lat": 40.779018153849094,
          "lng": -73.96460115909578,
          "x": -4059.815139591694,
          "y": 1622.196483016014
        },
        {
          "lat": 40.77888531343079,
          "lng": -73.96428799792379
        },
        {
          "lat": 40.779324021956874,
          "lng": -73.96396345063299
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434412578,
      "type": "restaurant",
      "subType": "restaurant-bar",
      "name": null,
      "points": [
        {
          "lat": 40.778683027998746,
          "lng": -73.96513760089876,
          "x": -5659.815139591694,
          "y": 2942.196483016014
        },
        {
          "lat": 40.779099396224886,
          "lng": -73.96484524011613,
          "x": -4787.815139591694,
          "y": 1302.1964829564095
        },
        {
          "lat": 40.778814501521666,
          "lng": -73.96413765112659
        },
        {
          "lat": 40.77839813150979,
          "lng": -73.96443001190922
        }
      ],
      "layerId": 1
    },
    {
      "id": 1774434446454,
      "type": "restroom",
      "subType": null,
      "name": null,
      "points": [
        {
          "lat": 40.77793762080246,
          "lng": -73.963380753994,
          "x": -419.8151395916939,
          "y": 5878.196483016014
        },
        {
          "lat": 40.77834790045769,
          "lng": -73.96308034658433,
          "x": 476.1848604083061,
          "y": 4262.196482956409
        },
        {
          "lat": 40.77852494556015,
          "lng": -73.96350202676534
        },
        {
          "lat": 40.778114666998405,
          "lng": -73.96380243417501
        }
      ],
      "layerId": 1
    }
  ],
  "pois": [
    {
      "id": 1774434384243,
      "type": "restaurant",
      "subType": "restaurant",
      "name": null,
      "position": {
        "lat": 40.78008469902747,
        "lng": -73.96358802437223
      },
      "layerId": 1
    },
    {
      "id": 1774434400219,
      "type": "restaurant",
      "subType": "bar",
      "name": null,
      "position": {
        "lat": 40.77917108768365,
        "lng": -73.96428230486438
      },
      "layerId": 1
    },
    {
      "id": 1774434412579,
      "type": "restaurant",
      "subType": "restaurant-bar",
      "name": null,
      "position": {
        "lat": 40.778748764313775,
        "lng": -73.96463762601267
      },
      "layerId": 1
    },
    {
      "id": 1774434420798,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77984682141991,
        "lng": -73.96416932344438,
        "x": -2771.815139591694,
        "y": -1641.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434421539,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.7799524351715,
        "lng": -73.96414786577226,
        "x": -2707.815139591694,
        "y": -2057.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434422183,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77990775245092,
        "lng": -73.96435976028444,
        "x": -3339.815139591694,
        "y": -1881.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434422854,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.7798062007015,
        "lng": -73.96445900201799,
        "x": -3635.815139591694,
        "y": -1481.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434423512,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77963762445471,
        "lng": -73.96439462900163,
        "x": -3443.815139591694,
        "y": -817.8035169839859
      },
      "layerId": 1
    },
    {
      "id": 1774434424870,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77944670626095,
        "lng": -73.96421223878862,
        "x": -2899.815139591694,
        "y": -65.80351692438126
      },
      "layerId": 1
    },
    {
      "id": 1774434425562,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77942639578253,
        "lng": -73.96404862403871,
        "x": -2411.815139591694,
        "y": 14.1964830160141
      },
      "layerId": 1
    },
    {
      "id": 1774434431178,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.77882926494136,
        "lng": -73.96291673183443,
        "x": 964.1848604083061,
        "y": 2366.196483016014
      },
      "layerId": 1
    },
    {
      "id": 1774434431767,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.778961284126936,
        "lng": -73.96284699440004,
        "x": 1172.1848604083061,
        "y": 1846.196483016014
      },
      "layerId": 1
    },
    {
      "id": 1774434432190,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.779070961404656,
        "lng": -73.96278798580171,
        "x": 1348.1848604083061,
        "y": 1414.196483016014
      },
      "layerId": 1
    },
    {
      "id": 1774434432946,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.77917860744558,
        "lng": -73.96273970603944,
        "x": 1492.1848604083061,
        "y": 990.1964830160141
      },
      "layerId": 1
    },
    {
      "id": 1774434433897,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.77927203594348,
        "lng": -73.962659239769,
        "x": 1732.1848604083061,
        "y": 622.1964830160141
      },
      "layerId": 1
    },
    {
      "id": 1774434434967,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.77914001737552,
        "lng": -73.96256804466249,
        "x": 2004.1848604083061,
        "y": 1142.1964829564095
      },
      "layerId": 1
    },
    {
      "id": 1774434435787,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.7789409735001,
        "lng": -73.96268874406816,
        "x": 1644.1848604083061,
        "y": 1926.1964828968048
      },
      "layerId": 1
    },
    {
      "id": 1774434436659,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.77937765060896,
        "lng": -73.96257877349855,
        "x": 1972.1848604083061,
        "y": 206.19648295640945
      },
      "layerId": 1
    },
    {
      "id": 1774434437242,
      "type": "exhibit",
      "subType": null,
      "name": "The Starry Night",
      "position": {
        "lat": 40.7795766931759,
        "lng": -73.96252244710924,
        "x": 2140.184860408306,
        "y": -577.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434446455,
      "type": "restroom",
      "subType": null,
      "name": null,
      "position": {
        "lat": 40.77823128345467,
        "lng": -73.96344139037967
      },
      "layerId": 1
    },
    {
      "id": 1774434477477,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.78059017617988,
        "lng": -73.96279335021974,
        "x": 1332.1848604083061,
        "y": -4569.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434477935,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.78051705968714,
        "lng": -73.96250635385515,
        "x": 2188.184860408306,
        "y": -4281.803517103195
      },
      "layerId": 1
    },
    {
      "id": 1774434478477,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.78043175701052,
        "lng": -73.96232128143312,
        "x": 2740.184860408306,
        "y": -3945.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434478934,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.780376919517714,
        "lng": -73.96204501390459,
        "x": 3564.184860408306,
        "y": -3729.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434479586,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.780301771768876,
        "lng": -73.96201819181444,
        "x": 3644.184860408306,
        "y": -3433.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434480154,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.78011694856541,
        "lng": -73.96195113658906,
        "x": 3844.184860408306,
        "y": -2705.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434480624,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.77993212484768,
        "lng": -73.96201550960542,
        "x": 3652.184860408306,
        "y": -1977.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434481327,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.77989759728299,
        "lng": -73.96223276853563,
        "x": 3004.184860408306,
        "y": -1841.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434481843,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.7800499246393,
        "lng": -73.96224349737169,
        "x": 2972.184860408306,
        "y": -2441.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434485088,
      "type": "exhibit",
      "subType": null,
      "name": "Venus de Milo",
      "position": {
        "lat": 40.78047237734639,
        "lng": -73.96367579698564,
        "x": -1299.8151395916939,
        "y": -4105.803517043591
      },
      "layerId": 1
    },
    {
      "id": 1774434486182,
      "type": "exhibit",
      "subType": null,
      "name": "Venus de Milo",
      "position": {
        "lat": 40.780649075518284,
        "lng": -73.9635255932808,
        "x": -851.8151395916939,
        "y": -4801.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434487029,
      "type": "exhibit",
      "subType": null,
      "name": "Venus de Milo",
      "position": {
        "lat": 40.78079124611995,
        "lng": -73.96343171596529,
        "x": -571.8151395916939,
        "y": -5361.803517043591
      },
      "layerId": 1
    },
    {
      "id": 1774434519111,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77926391173149,
        "lng": -73.96330028772356,
        "x": -179.81513959169388,
        "y": 654.1964830160141
      },
      "layerId": 1
    },
    {
      "id": 1774434520833,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.779976807551854,
        "lng": -73.96320641040803,
        "x": 100.18486040830612,
        "y": -2153.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434526048,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.78029364768281,
        "lng": -73.9628040790558,
        "x": 1300.1848604083061,
        "y": -3401.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434527668,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.78019209652337,
        "lng": -73.96313667297365,
        "x": 308.1848604083061,
        "y": -3001.8035170435905
      },
      "layerId": 1
    },
    {
      "id": 1774434528767,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77996259033106,
        "lng": -73.96256536245347,
        "x": 2012.1848604083061,
        "y": -2097.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434530811,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.778741929028236,
        "lng": -73.96371334791185,
        "x": -1411.8151395916939,
        "y": 2710.196483016014
      },
      "layerId": 1
    },
    {
      "id": 1774434534217,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.780695788749526,
        "lng": -73.9630374312401,
        "x": 604.1848604083061,
        "y": -4985.803516983986
      },
      "layerId": 1
    },
    {
      "id": 1774434536063,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77829712341002,
        "lng": -73.96420419216157,
        "x": -2875.815139591694,
        "y": 4462.196483016014
      },
      "layerId": 1
    },
    {
      "id": 1774466853918,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.779700586717425,
        "lng": -73.96453946828844,
        "x": -3875.815139591694,
        "y": -1065.803516983986
      },
      "layerId": 2
    },
    {
      "id": 1774466855249,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.77994837310724,
        "lng": -73.96435439586641,
        "x": -3323.815139591694,
        "y": -2041.8035170435905
      },
      "layerId": 2
    },
    {
      "id": 1774466856497,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.78050487359717,
        "lng": -73.96366238594057,
        "x": -1259.8151395916939,
        "y": -4233.803516983986
      },
      "layerId": 2
    },
    {
      "id": 1774466857223,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.78075062597909,
        "lng": -73.96347999572755,
        "x": -715.8151395916939,
        "y": -5201.803516983986
      },
      "layerId": 2
    },
    {
      "id": 1774466858556,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.78058408314189,
        "lng": -73.96276652812959,
        "x": 1412.1848604083061,
        "y": -4545.803516983986
      },
      "layerId": 2
    },
    {
      "id": 1774466859341,
      "type": "exhibit",
      "subType": null,
      "name": "Mona Lisa",
      "position": {
        "lat": 40.780338330143785,
        "lng": -73.96214425563814,
        "x": 3268.184860408306,
        "y": -3577.803516983986
      },
      "layerId": 2
    },
    {
      "id": 1774466863027,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.77983463520701,
        "lng": -73.96239638328554,
        "x": 2516.184860408306,
        "y": -1593.8035170435905
      },
      "layerId": 2
    },
    {
      "id": 1774466863666,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.7794548304506,
        "lng": -73.96260827779771,
        "x": 1884.1848604083061,
        "y": -97.8035169839859
      },
      "layerId": 2
    },
    {
      "id": 1774466864475,
      "type": "exhibit",
      "subType": null,
      "name": "Girl with a Pearl Earring",
      "position": {
        "lat": 40.779205011164834,
        "lng": -73.9626055955887,
        "x": 1892.1848604083061,
        "y": 886.1964830160141
      },
      "layerId": 2
    },
    {
      "id": 1774466889408,
      "type": "exit",
      "subType": "normal",
      "name": null,
      "position": {
        "lat": 40.77968230735697,
        "lng": -73.96410763263704,
        "x": -2587.815139591694,
        "y": -993.8035169839859
      },
      "layerId": 2
    }
  ]
}

const transformDataForCanvas = (data, canvasSize = 500, padding = 40) => {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  const zoom = 22; // Must match Editor zoom level for scale match

  const ensureXY = (pt) => {
    if (pt && pt.lat !== undefined && pt.lng !== undefined && (pt.x === undefined || pt.y === undefined)) {
      const centerPt = data.museumCenter || [40.77943, -73.96324];
      const origin = L.CRS.EPSG3857.latLngToPoint(L.latLng(centerPt[0], centerPt[1]), zoom);
      const target = L.CRS.EPSG3857.latLngToPoint(L.latLng(pt.lat, pt.lng), zoom);
      pt.x = target.x - origin.x;
      pt.y = target.y - origin.y;
    }
    return pt;
  };

  if (data.lines) {
    data.lines.forEach(line => line.points.forEach(pt => {
      ensureXY(pt);
      if (pt.x < minX) minX = pt.x; if (pt.x > maxX) maxX = pt.x;
      if (pt.y < minY) minY = pt.y; if (pt.y > maxY) maxY = pt.y;
    }));
  }

  if (data.pois) {
    data.pois.forEach(poi => {
      ensureXY(poi.position);
      if (poi.position.x < minX) minX = poi.position.x; if (poi.position.x > maxX) maxX = poi.position.x;
      if (poi.position.y < minY) minY = poi.position.y; if (poi.position.y > maxY) maxY = poi.position.y;
    });
  }

  if (data.areas) {
    data.areas.forEach(area => area.points.forEach(pt => {
      ensureXY(pt);
      if (pt.x !== undefined && pt.y !== undefined) {
        if (pt.x < minX) minX = pt.x; if (pt.x > maxX) maxX = pt.x;
        if (pt.y < minY) minY = pt.y; if (pt.y > maxY) maxY = pt.y;
      }
    }));
  }

  if (minX === Infinity) return { scale: 1, offsetX: 0, offsetY: 0 };

  const width = Math.max(maxX - minX, 1);
  const height = Math.max(maxY - minY, 1);
  const drawArea = canvasSize - padding * 2;
  const scale = drawArea / Math.max(width, height);
  const offsetX = (canvasSize - (width * scale)) / 2 - minX * scale;
  const offsetY = (canvasSize - (height * scale)) / 2 - minY * scale;

  return { scale, offsetX, offsetY };
};

export default function NavigatorApp() {
  const [museumData, setMuseumData] = useState(mockMuseumData);
  const [items, setItems] = useState([]);

  useEffect(() => {
    const loadData = async () => {
      const data = await fetchMuseumData();
      setMuseumData(data);
    };
    loadData();
  }, []);

  const { scale, offsetX, offsetY } = useMemo(() => transformDataForCanvas(museumData), [museumData]);
  const tx = useCallback((x) => x * scale + offsetX, [scale, offsetX]);
  const ty = useCallback((y) => y * scale + offsetY, [scale, offsetY]);

  const location = useLocation();
  const navigate = useNavigate();
  const canvasRef = useRef(null);

  const searchParams = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const visitId = searchParams.get('visitId') || location.state?.visitId || location.state?.id;

  const [activeVisitTitle, setActiveVisitTitle] = useState(location.state?.museum || 'Tour Pinacoteca');
  const [authError, setAuthError] = useState(null);

  // 1. Authentication Check (Must be logged in to access the tour)
  useEffect(() => {
    const token = localStorage.getItem('apiToken') || localStorage.getItem('token');
    const user = localStorage.getItem('user') || localStorage.getItem('userData');
    if (!token && !user) {
      setAuthError('Accesso riservato: effettua il login per accedere al tour del museo.');
    }
  }, []);

  // 2. Load Visit Data if visitId is provided, otherwise fallback to museum exhibits
  useEffect(() => {
    if (visitId) {
      fetch(`/api/v1/navigator/visits/get/${visitId}`)
        .then(res => res.json())
        .then(data => {
          if (data && (data._id || data.title)) {
            if (data.title) setActiveVisitTitle(data.title);
            if (data.quiz) setActiveQuizData(data.quiz);

            if (data.items && data.items.length > 0) {
              const loadedItems = data.items.map((it, idx) => ({
                id: it._id || idx,
                artworkId: it.artworkId,
                name: it.title || it.name,
                desc: it.description || it.desc || `Stai esplorando l'opera ${it.title}.`,
                artist: it.author || it.creator?.username || 'Pinacoteca Nazionale di Bologna',
                image: it.image || 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=500',
                x: it.position?.x !== undefined ? tx(it.position.x) : (tx(100) + (idx % 4) * 50),
                y: it.position?.y !== undefined ? ty(it.position.y) : (ty(100) + Math.floor(idx / 4) * 50),
                layerId: it.layerId || 1
              }));
              setItems(loadedItems);
              return;
            }
          }
          // Fallback to exhibits from museumData
          loadMuseumExhibits();
        })
        .catch(err => {
          console.warn("Errore caricamento visita specifica, uso opere museo:", err);
          loadMuseumExhibits();
        });
    } else {
      loadMuseumExhibits();
    }

    function loadMuseumExhibits() {
      const tourItems = (museumData.pois || [])
        .filter(poi => poi.type === 'exhibit')
        .map(poi => ({
          id: poi.id,
          name: poi.name,
          desc: poi.desc || `Stai esplorando l'opera ${poi.name}.`,
          artist: 'Pinacoteca Nazionale di Bologna',
          image: poi.image || 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=500',
          x: tx(poi.position.x),
          y: ty(poi.position.y),
          layerId: poi.layerId
        }));
      setItems(tourItems);
    }
  }, [visitId, museumData, tx, ty]);

  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [showDescription, setShowDescription] = useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const [showMoreMenu, setShowMoreMenu] = useState(false);
  const [isVoiceModalOpen, setIsVoiceModalOpen] = useState(false);
  const [isAccessibilityModalOpen, setIsAccessibilityModalOpen] = useState(false);
  const [accessibleRoute, setAccessibleRoute] = useState(false);
  const [fontSizeMultiplier, setFontSizeMultiplier] = useState(1);
  const [speechRate, setSpeechRate] = useState(1.0);
  const [autoPlayAudio, setAutoPlayAudio] = useState(false);
  const [highContrast, setHighContrast] = useState(false);
  const [notificationToast, setNotificationToast] = useState(null);
  const [hasTriggeredCurrent, setHasTriggeredCurrent] = useState(false);

  // Synchronized Tour & Socket.io States
  const [isSyncModalOpen, setIsSyncModalOpen] = useState(false);
  const [isQuizModalOpen, setIsQuizModalOpen] = useState(false);
  const [activeQuizData, setActiveQuizData] = useState(null);
  const [isTeacherMode, setIsTeacherMode] = useState(false);
  const [isSyncedVisitor, setIsSyncedVisitor] = useState(false);
  const [activeMnemonic, setActiveMnemonic] = useState('');
  const [connectedVisitorsCount, setConnectedVisitorsCount] = useState(0);
  const [teacherQuizResults, setTeacherQuizResults] = useState([]);
  const socketRef = useRef(null);

  const showToast = (message) => {
    setNotificationToast(message);
    setTimeout(() => {
      setNotificationToast(null);
    }, 4500);
  };

  // TTS Speaker
  const { speak, pause: pauseSpeaking, stop: stopSpeaking, seek, isSpeaking, currentTime, duration } = useSpeaker();

  // Keep isPlaying in sync with TTS state
  useEffect(() => {
    setIsPlaying(isSpeaking);
  }, [isSpeaking]);

  // Pathfinding and Navigation States
  const [collisionGrid, setCollisionGrid] = useState(null);
  const [currentPath, setCurrentPath] = useState([]);
  const [mapZoom, setMapZoom] = useState(4.5);
  const moveIntervalRef = useRef(null);

  // Layer Management
  const [activeLayerId, setActiveLayerId] = useState(museumData?.layers?.[0]?.id || 1);

  const currentItem = items[currentIndex];

  // Sync active layer when current exhibit changes
  useEffect(() => {
    if (currentItem?.layerId && currentItem.layerId !== activeLayerId) {
      setActiveLayerId(currentItem.layerId);
    }
  }, [currentIndex, currentItem, activeLayerId]);

  // Native Full-Screen Scale
  const [windowSize, setWindowSize] = useState({ w: window.innerWidth, h: window.innerHeight });

  useEffect(() => {
    const handleResize = () => setWindowSize({ w: window.innerWidth, h: window.innerHeight });
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Camera and Panning state
  const [isTrackingUser, setIsTrackingUser] = useState(true);
  const [cameraPos, setCameraPos] = useState({ x: 250, y: 250 });
  const [isPanning, setIsPanning] = useState(false);
  const lastPanRef = useRef({ x: 0, y: 0 });

  // User simulated position (started near the first exhibit)
  const startPos = items?.length > 0 ? { x: items[0].x, y: items[0].y + 40 } : { x: 250, y: 250 };
  const [userPos, setUserPos] = useState(startPos);

  const handleSelectTarget = (poi) => {
    if (!poi || !poi.position) return;
    if (poi.type === 'exhibit') {
      const idx = items.findIndex(it => it.id === poi.id || (poi.artworkId && it.artworkId === poi.artworkId));
      if (idx !== -1) {
        setCurrentIndex(idx);
        showToast(`🎯 Opera selezionata: ${poi.name}`);
      }
    }
  };

  useEffect(() => {
    const layerLines = (museumData.lines || []).filter(l => l.layerId === activeLayerId);
    const extWalls = (museumData.lines || []).filter(l => l.type === 'ext-wall');
    const colsLines = layerLines.some(l => l.type === 'ext-wall') ? layerLines : [...extWalls, ...layerLines];

    setCollisionGrid(createCollisionGrid(
      colsLines,
      (museumData.pois || []).filter(p => p.layerId === activeLayerId),
      tx, ty
    ));
  }, [activeLayerId, museumData, tx, ty]);

  useEffect(() => {
    if (collisionGrid && currentItem) {
      setCurrentPath(findPath(collisionGrid, userPos, { x: currentItem.x, y: currentItem.y }));
    }
  }, [userPos, currentItem, collisionGrid]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');

    // Clear background
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.save(); // Save default context state
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';

    // Camera Transform System
    const cameraX = isTrackingUser ? userPos.x : cameraPos.x;
    const cameraY = isTrackingUser ? userPos.y : cameraPos.y;

    // Always apply transforms so zooming and panning is centered out of the box
    // 1. Move origin to canvas center
    ctx.translate(canvas.width / 2, canvas.height / 2);
    // 2. Scale up
    ctx.scale(mapZoom, mapZoom);
    // 3. Move origin back, offset by Camera Pos
    ctx.translate(-cameraX, -cameraY);

    // Draw high-end grid background
    const gridSize = 100;
    ctx.beginPath();
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.03)';
    ctx.lineWidth = 1 / mapZoom;
    for (let x = -2000; x <= 4000; x += gridSize) {
      ctx.moveTo(x, -8000); ctx.lineTo(x, 2000);
    }
    for (let y = -8000; y <= 2000; y += gridSize) {
      ctx.moveTo(-2000, y); ctx.lineTo(4000, y);
    }
    ctx.stroke();

    // Draw Floor Fill based on external walls
    if (museumData.lines) {
      const extWalls = museumData.lines.filter(l => l.type === 'ext-wall');
      const layerExtWalls = extWalls.filter(l => l.layerId === activeLayerId);
      const renderExtWalls = layerExtWalls.length > 0 ? layerExtWalls : extWalls; // fallback to base building footprint

      renderExtWalls.forEach(line => {
        ctx.beginPath();
        line.points.forEach((pt, i) => {
          const cx = tx(pt.x);
          const cy = ty(pt.y);
          if (i === 0) ctx.moveTo(cx, cy); else ctx.lineTo(cx, cy);
        });
        ctx.fillStyle = '#1c1b1b'; // Obsidian surface
        ctx.fill();
      });
    }

    // Draw Areas Interactively (if defined in JSON)
    if (museumData.areas) {
      museumData.areas.filter(a => a.layerId === activeLayerId).forEach(area => {
        ctx.beginPath();
        area.points.forEach((pt, i) => {
          const cx = tx(pt.x);
          const cy = ty(pt.y);
          if (i === 0) ctx.moveTo(cx, cy); else ctx.lineTo(cx, cy);
        });
        ctx.closePath();

        ctx.save();
        if (area.type === 'restaurant') {
          ctx.fillStyle = 'rgba(245, 158, 11, 0.15)'; // Beautiful translucent Amber
          ctx.strokeStyle = 'rgba(245, 158, 11, 0.6)';
        } else if (area.type === 'restroom') {
          ctx.fillStyle = 'rgba(14, 165, 233, 0.15)'; // Beautiful translucent Sky Blue
          ctx.strokeStyle = 'rgba(14, 165, 233, 0.6)';
        } else {
          ctx.fillStyle = 'rgba(148, 163, 184, 0.15)';
          ctx.strokeStyle = 'rgba(148, 163, 184, 0.6)';
        }

        ctx.lineWidth = 1.5 / mapZoom;
        ctx.fill();
        ctx.shadowColor = ctx.strokeStyle;
        ctx.shadowBlur = 12 / mapZoom;
        ctx.stroke();
        ctx.restore();
      });
    }

    // Draw lines (walls) from JSON
    if (museumData.lines) {
      const extWalls = museumData.lines.filter(l => l.type === 'ext-wall');
      const layerExtWalls = extWalls.filter(l => l.layerId === activeLayerId);
      const renderExtWalls = layerExtWalls.length > 0 ? layerExtWalls : extWalls; // fallback to base building footprint

      const internalWalls = museumData.lines.filter(l => l.type !== 'ext-wall' && l.layerId === activeLayerId);

      [...renderExtWalls, ...internalWalls].forEach(line => {
        ctx.beginPath();
        line.points.forEach((pt, i) => {
          const cx = tx(pt.x);
          const cy = ty(pt.y);
          if (i === 0) ctx.moveTo(cx, cy);
          else ctx.lineTo(cx, cy);
        });

        const isExt = line.type === 'ext-wall';
        ctx.strokeStyle = isExt ? '#000000' : '#334155';
        ctx.lineWidth = isExt ? 8 / (mapZoom * 0.7) : 3 / (mapZoom * 0.7);

        if (isExt) {
          ctx.shadowColor = 'rgba(0,0,0,0.5)';
          ctx.shadowBlur = 15 / (mapZoom * 0.7);
        }
        ctx.stroke();
        ctx.shadowBlur = 0; // Reset shadow
      });
    }

    // Draw POIs (Non-exhibits) from JSON
    if (museumData.pois) {
      museumData.pois.filter(p => p.layerId === activeLayerId).forEach(poi => {
        if (poi.type === 'exhibit' || !poi.position) return; // Handled below in tour items

        const cx = tx(poi.position.x);
        const cy = ty(poi.position.y);

        // Match Editor.jsx HTML box styling exactly
        let label = 'EX';
        let bgColor = '#8b5cf6'; // exhibit

        if (poi.type === 'exit') {
          label = poi.subType === 'emergency' ? 'SOS' : 'Exit';
          bgColor = poi.subType === 'emergency' ? '#ef4444' : '#10b981';
        } else if (poi.type === 'restaurant') {
          label = poi.subType === 'bar' ? 'Bar' : poi.subType === 'restaurant-bar' ? 'R&B' : 'Café';
          bgColor = '#f59e0b';
        } else if (poi.type === 'restroom') {
          label = 'WC';
          bgColor = '#0ea5e9';
        }

        ctx.save();
        ctx.shadowColor = 'rgba(0,0,0,0.3)';
        ctx.shadowBlur = 8 / mapZoom;
        ctx.fillStyle = bgColor;
        const boxW = 26 / mapZoom;
        const boxH = 18 / mapZoom;
        ctx.beginPath();
        ctx.roundRect(cx - boxW / 2, cy - boxH / 2, boxW, boxH, 8 / mapZoom);
        ctx.fill();

        ctx.lineWidth = 1.5 / mapZoom;
        ctx.strokeStyle = '#ffffff';
        ctx.stroke();
        ctx.restore();

        ctx.fillStyle = 'white';
        ctx.font = `bold ${9 / mapZoom}px sans-serif`;
        ctx.textBaseline = 'middle';
        ctx.textAlign = 'center';
        ctx.fillText(label, cx, cy + (1 / mapZoom));
      });
    }

    // Draw current routing path
    if (currentPath.length > 0) {
      ctx.beginPath();
      ctx.moveTo(userPos.x, userPos.y);
      currentPath.forEach((pt) => ctx.lineTo(pt.x, pt.y));
      ctx.strokeStyle = '#b7c4ff'; // Electric Blue Primary
      ctx.lineWidth = 5 / mapZoom;
      ctx.setLineDash([12 / mapZoom, 8 / mapZoom]);
      ctx.globalAlpha = 0.8;
      ctx.stroke();
      ctx.globalAlpha = 1.0;
      ctx.setLineDash([]);
    }

    // Draw active Tour Items (Exhibits)
    items.forEach((item, index) => {
      const poi = (museumData.pois || []).find(p => p.id === item.id);
      if (poi && poi.layerId !== activeLayerId) return; // Only show exhibits on current layer

      const isActive = index === currentIndex;
      const cx = item.x;
      const cy = item.y;
      const label = 'Ex';
      const bgColor = isActive ? '#b7c4ff' : 'rgba(255, 255, 255, 0.2)'; 

      ctx.save();
      ctx.shadowColor = 'rgba(0,0,0,0.3)';
      ctx.shadowBlur = 8 / mapZoom;
      ctx.fillStyle = bgColor;
      const boxW = (isActive ? 32 : 28) / mapZoom;
      const boxH = (isActive ? 20 : 16) / mapZoom;
      const radius = 6 / mapZoom;

      ctx.beginPath();
      ctx.roundRect(cx - boxW / 2, cy - boxH / 2, boxW, boxH, radius);
      ctx.fill();

      if (isActive) {
        ctx.lineWidth = 2 / mapZoom;
        ctx.strokeStyle = '#ffffff';
        ctx.stroke();

        // Glow for active
        ctx.beginPath();
        ctx.roundRect(cx - (boxW + 6 / mapZoom) / 2, cy - (boxH + 6 / mapZoom) / 2, boxW + 6 / mapZoom, boxH + 6 / mapZoom, radius + 2 / mapZoom);
        ctx.strokeStyle = 'rgba(183, 196, 255, 0.4)';
        ctx.lineWidth = 3 / mapZoom;
        ctx.stroke();
      }
      ctx.restore();

      ctx.fillStyle = isActive ? '#131313' : 'white';
      ctx.font = `bold ${(isActive ? 11 : 10) / mapZoom}px var(--font-label)`;
      ctx.textBaseline = 'middle';
      ctx.textAlign = 'center';
      ctx.fillText(label, cx, cy + (1 / mapZoom));
    });



    ctx.restore(); // Undo camera transforms

  }, [currentIndex, items, userPos, cameraPos, mapZoom, isTrackingUser, windowSize, activeLayerId, museumData, tx, ty]);

  // Proximity Auto-Trigger Pop-up
  useEffect(() => {
    if (currentItem && !hasTriggeredCurrent) {
      const dx = userPos.x - currentItem.x;
      const dy = userPos.y - currentItem.y;
      const distance = Math.sqrt(dx * dx + dy * dy);
      if (distance < 20) {
        // Fire the ItemDescription component overlay Pop-Up
        setShowPopup(true);
        setHasTriggeredCurrent(true);
      }
    }
  }, [userPos, currentItem, hasTriggeredCurrent]);

  // Reset auto-trigger and audio when moving to next item
  useEffect(() => {
    setHasTriggeredCurrent(false);
    setShowPopup(false); 
    stopSpeaking(); 
  }, [currentIndex, stopSpeaking]);

  // Controller Logic (Smooth, Sliding Collision & Keyboard Support)
  const moveUser = (dx, dy) => {
    setUserPos(prev => {
      const step = 6;
      const nx = prev.x + dx * step;
      const ny = prev.y + dy * step;

      if (!collisionGrid) return { x: nx, y: ny };

      const c = Math.floor(nx / collisionGrid.gridSize);
      const r = Math.floor(ny / collisionGrid.gridSize);

      if (c >= 0 && c < collisionGrid.cols && r >= 0 && r < collisionGrid.rows) {
        if (collisionGrid.grid[r] && collisionGrid.grid[r][c] === 0) {
          return { x: nx, y: ny };
        }
        // Try sliding horizontally
        const rY = Math.floor(prev.y / collisionGrid.gridSize);
        if (collisionGrid.grid[rY] && collisionGrid.grid[rY][c] === 0) {
          return { x: nx, y: prev.y };
        }
        // Try sliding vertically
        const cX = Math.floor(prev.x / collisionGrid.gridSize);
        if (collisionGrid.grid[r] && collisionGrid.grid[r][cX] === 0) {
          return { x: prev.x, y: ny };
        }
      }
      return prev;
    });
  };

  const startMove = (dx, dy) => {
    if (moveIntervalRef.current) clearInterval(moveIntervalRef.current);
    setIsPlaying(false);
    setIsTrackingUser(true);
    moveUser(dx, dy);
    moveIntervalRef.current = setInterval(() => moveUser(dx, dy), 40);
  };

  const stopMove = () => {
    if (moveIntervalRef.current) {
      clearInterval(moveIntervalRef.current);
      moveIntervalRef.current = null;
    }
  };

  // Keyboard Controller Support (Arrow keys / WASD)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName)) return;
      if (['ArrowUp', 'KeyW', 'w', 'W'].includes(e.key || e.code)) {
        setIsTrackingUser(true);
        moveUser(0, -1);
      } else if (['ArrowDown', 'KeyS', 's', 'S'].includes(e.key || e.code)) {
        setIsTrackingUser(true);
        moveUser(0, 1);
      } else if (['ArrowLeft', 'KeyA', 'a', 'A'].includes(e.key || e.code)) {
        setIsTrackingUser(true);
        moveUser(-1, 0);
      } else if (['ArrowRight', 'KeyD', 'd', 'D'].includes(e.key || e.code)) {
        setIsTrackingUser(true);
        moveUser(1, 0);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [collisionGrid]);

  // Canvas Panning Controls
  const handlePointerDown = (e) => {
    e.preventDefault();
    setIsPanning(true);
    // Unbind camera from user dot on touch layout
    if (isTrackingUser) {
      setIsTrackingUser(false);
      setCameraPos(userPos);
    }
    lastPanRef.current = { x: e.clientX, y: e.clientY };
  };

  const handlePointerMove = (e) => {
    if (!isPanning) return;
    const dx = e.clientX - lastPanRef.current.x;
    const dy = e.clientY - lastPanRef.current.y;
    lastPanRef.current = { x: e.clientX, y: e.clientY };

    // Move camera relative to zoom factor
    // Loosen clamps to allow freer exploration of the large map
    setCameraPos(prev => ({
      x: prev.x - dx / mapZoom,
      y: prev.y - dy / mapZoom
    }));
  };

  const handlePointerUp = () => {
    setIsPanning(false);
  };

  const handleNext = () => {
    if (currentIndex < items.length - 1) {
      setCurrentIndex(prev => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex(prev => prev - 1);
    }
  };

  const togglePlay = () => {
    if (isSpeaking) {
      pauseSpeaking();
    } else if (currentItem?.desc) {
      speak(currentItem.desc, currentItem.id);
    }
  };

  const handleSeekBack = () => seek(Math.max(0, currentTime - 5));
  const handleSeekForward = () => seek(Math.min(duration || 9999, currentTime + 5));

  // Initialize Socket.io connection
  useEffect(() => {
    const socket = io('/sync-tour', {
      transports: ['websocket', 'polling']
    });
    socketRef.current = socket;

    socket.on('connect', () => {
      console.log('Connected to /sync-tour websocket');
    });

    socket.on('sync:state_changed', (data) => {
      if (data) {
        if (data.currentIndex !== undefined) setCurrentIndex(data.currentIndex);
        if (data.activeLayerId !== undefined) setActiveLayerId(data.activeLayerId);
        if (data.userPos) setUserPos(data.userPos);
        if (data.isPlaying && currentItem?.desc) {
          speak(currentItem.desc, currentItem.id);
        }
        if (data.message) {
          showToast(`📡 Docente: ${data.message}`);
        }
      }
    });

    socket.on('sync:participant_count', (data) => {
      if (data && data.count !== undefined) {
        setConnectedVisitorsCount(data.count);
        if (data.visitorName) {
          showToast(`👤 ${data.visitorName} si è unito alla visita!`);
        }
      }
    });

    socket.on('sync:quiz_started', (data) => {
      if (data && data.quiz) {
        setActiveQuizData(data.quiz);
        setIsQuizModalOpen(true);
        showToast("📝 Il Docente ha avviato il Quiz di fine visita!");
      }
    });

    socket.on('teacher:quiz_result', (data) => {
      if (data && data.allResults) {
        setTeacherQuizResults(data.allResults);
        showToast(`📊 Quiz consegnato da ${data.result.visitorName}: ${data.result.score}/${data.result.total}`);
      }
    });

    return () => {
      socket.disconnect();
    };
  }, [currentItem, speak]);

  const handleStartTeacherSession = (mnemonic) => {
    const name = mnemonic || 'Fenice rossa';
    setActiveMnemonic(name);
    setIsTeacherMode(true);
    setIsSyncedVisitor(false);
    if (socketRef.current) {
      socketRef.current.emit('teacher:create_session', {
        mnemonicName: name,
        museumId: 'PIN-BO'
      });
    }
    showToast(`🎓 Sessione Docente avviata: "${name}"`);
  };

  const handleJoinVisitorSession = (mnemonic, visitorName) => {
    const name = mnemonic || 'Fenice rossa';
    setActiveMnemonic(name);
    setIsSyncedVisitor(true);
    setIsTeacherMode(false);
    if (socketRef.current) {
      socketRef.current.emit('visitor:join_session', {
        mnemonicName: name,
        visitorName: visitorName || 'Studente'
      });
    }
    showToast(`🟢 Sincronizzato con la stanza "${name}"`);
  };

  const handleLeaveSyncSession = () => {
    setIsTeacherMode(false);
    setIsSyncedVisitor(false);
    setActiveMnemonic('');
    showToast("Sessione sincronizzata terminata");
  };

  const handleBroadcastState = (type) => {
    if (!socketRef.current || !activeMnemonic) return;
    if (type === 'POS') {
      socketRef.current.emit('teacher:update_state', {
        mnemonicName: activeMnemonic,
        userPos,
        activeLayerId,
        message: 'Posizione gruppo aggiornata sulla mappa.'
      });
      showToast("📡 Posizione trasmessa a tutti gli studenti");
    } else if (type === 'NEXT') {
      if (currentIndex < items.length - 1) {
        const nextIdx = currentIndex + 1;
        setCurrentIndex(nextIdx);
        socketRef.current.emit('teacher:update_state', {
          mnemonicName: activeMnemonic,
          currentIndex: nextIdx,
          userPos,
          activeLayerId,
          message: 'Passaggio alla prossima opera.'
        });
      }
    } else if (type === 'PREV') {
      if (currentIndex > 0) {
        const prevIdx = currentIndex - 1;
        setCurrentIndex(prevIdx);
        socketRef.current.emit('teacher:update_state', {
          mnemonicName: activeMnemonic,
          currentIndex: prevIdx,
          userPos,
          activeLayerId,
          message: 'Passaggio all\'opera precedente.'
        });
      }
    } else if (type === 'AUDIO') {
      if (currentItem?.desc) {
        speak(currentItem.desc, currentItem.id);
      }
      socketRef.current.emit('teacher:update_state', {
        mnemonicName: activeMnemonic,
        isPlaying: true,
        message: 'Avvio spiegazione audio per il gruppo.'
      });
      showToast("🔊 Audio avviato su tutti i dispositivi");
    }
  };

  const handleStartGroupQuiz = () => {
    if (!socketRef.current || !activeMnemonic) return;
    socketRef.current.emit('teacher:start_quiz', {
      mnemonicName: activeMnemonic
    });
    showToast("📝 Quiz inviato a tutti i dispositivi!");
  };

  const handleSubmitQuizResults = (results) => {
    if (socketRef.current && activeMnemonic) {
      socketRef.current.emit('visitor:submit_quiz', {
        mnemonicName: activeMnemonic,
        score: results.score,
        total: results.total,
        answers: results.answers
      });
    }
  };

  // Voice Command Dispatcher (Web Speech API)
  const handleVoiceCommand = useCallback((cmd) => {
    if (!cmd) return;
    switch (cmd.type) {
      case 'NAV_NEXT':
        if (currentIndex < items.length - 1) {
          setCurrentIndex(prev => prev + 1);
        }
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'NAV_PREV':
        if (currentIndex > 0) {
          setCurrentIndex(prev => prev - 1);
        }
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'AUDIO_PLAY':
        if (currentItem?.desc) {
          speak(currentItem.desc, currentItem.id);
        }
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'AUDIO_PAUSE':
        pauseSpeaking();
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'AUDIO_REPLAY':
        seek(0);
        if (currentItem?.desc) speak(currentItem.desc, currentItem.id);
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'UI_EXPAND':
        setShowDescription(true);
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'UI_COLLAPSE':
        setShowDescription(false);
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'TELEPORT_EXHIBIT':
      case 'TELEPORT_FACILITY':
        if (cmd.target) {
          handleSelectTarget(cmd.target);
          showToast("🗣️ " + cmd.feedback);
        }
        break;
      case 'CHANGE_LAYER':
        setActiveLayerId(cmd.layerId);
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'TOGGLE_ACCESSIBILITY':
        setAccessibleRoute(prev => !prev);
        showToast("🗣️ " + cmd.feedback);
        break;
      case 'SHOW_HELP':
        setIsVoiceModalOpen(true);
        break;
      default:
        if (cmd.feedback) showToast("🗣️ " + cmd.feedback);
        break;
    }
  }, [currentIndex, items.length, currentItem, speak, pauseSpeaking, seek, handleSelectTarget]);

  const {
    isListening,
    transcript,
    lastFeedback,
    startListening,
    stopListening,
    executeManualCommand
  } = useSpeechRecognition({
    onCommand: handleVoiceCommand,
    pois: museumData.pois || [],
    currentIndex,
    itemsLength: items.length
  });

  const handleMicRequest = () => {
    setIsVoiceModalOpen(true);
  };

  const getScreenCoords = (abstractX, abstractY) => {
    const cx = isTrackingUser ? userPos.x : cameraPos.x;
    const cy = isTrackingUser ? userPos.y : cameraPos.y;
    return {
      x: windowSize.w / 2 + (abstractX - cx) * mapZoom,
      y: windowSize.h / 2 + (abstractY - cy) * mapZoom
    };
  };

  const userScreenPos = getScreenCoords(userPos.x, userPos.y);

  return (
    <div className="navigator-container">
      {/* Auth Barrier Overlay */}
      {authError && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0,0,0,0.85)',
          backdropFilter: 'blur(8px)',
          zIndex: 9999,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '20px'
        }}>
          <div style={{
            background: '#18181b',
            border: '1px solid #27272a',
            borderRadius: '20px',
            padding: '30px',
            maxWidth: '420px',
            width: '100%',
            textAlign: 'center',
            color: '#fff',
            boxShadow: '0 25px 50px -12px rgba(0,0,0,0.5)'
          }}>
            <div style={{ fontSize: '40px', marginBottom: '15px' }}>🔒</div>
            <h3 style={{ fontSize: '20px', fontWeight: 'bold', marginBottom: '10px' }}>Accesso Riservato</h3>
            <p style={{ fontSize: '14px', color: '#a1a1aa', marginBottom: '25px', lineHeight: 1.5 }}>
              {authError}
            </p>
            <button 
              onClick={() => window.location.href = '/marketplace/login'}
              style={{
                width: '100%',
                padding: '12px',
                background: '#7c3aed',
                color: '#fff',
                fontWeight: 'bold',
                borderRadius: '12px',
                border: 'none',
                cursor: 'pointer',
                fontSize: '15px'
              }}
            >
              Effettua il Login
            </button>
          </div>
        </div>
      )}

      <div className="navigator-header">
        <button className="back-btn" onClick={() => navigate(-1)}>
          <ArrowLeft size={24} />
        </button>
        <h2>{activeVisitTitle}</h2>
        <div style={{ width: 24 }}></div> {/* spacer */}
      </div>

      <div className="map-view-area">
        <div className="map-instructions">
          Target: <strong>{currentItem?.name || 'Initializing...'}</strong>
        </div>




        <canvas
          ref={canvasRef}
          width={windowSize.w}
          height={windowSize.h}
          className="indoor-canvas"
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerLeave={handlePointerUp}
        />

        {/* Dynamic User Pointer Overlay */}
        <div
          className="user-pulse-marker"
          style={{ left: userScreenPos.x, top: userScreenPos.y }}
        >
          <div className="pulse-ring"></div>
          <div className="pulse-core"></div>
        </div>

        {notificationToast && (
          <div className="teleport-toast-notification slide-in-top">
            <span>{notificationToast}</span>
            <button onClick={() => setNotificationToast(null)}><X size={14} /></button>
          </div>
        )}

        {/* Left Side Utility Buttons for 18-27 Track */}
        <div className="utility-buttons-left">
          <button
            className={`util-btn ${isSyncModalOpen || isSyncedVisitor || isTeacherMode ? 'active' : ''}`}
            onClick={() => setIsSyncModalOpen(true)}
            title="Visita Sincronizzata Real-Time (Docente/Studenti)"
            style={isSyncedVisitor || isTeacherMode ? { background: '#10b981', color: '#fff' } : { background: 'rgba(16, 185, 129, 0.15)', color: '#fff' }}
          >
            <Radio size={22} color={isSyncedVisitor || isTeacherMode ? '#fff' : '#34d399'} className={isSyncedVisitor || isTeacherMode ? 'animate-pulse' : ''} />
          </button>

          <button
            className={`util-btn ${isVoiceModalOpen ? 'active' : ''}`}
            onClick={() => setIsVoiceModalOpen(true)}
            title="Comandi Vocali Web Speech API"
            style={{ background: isListening ? '#ef4444' : 'rgba(239, 68, 68, 0.15)', color: '#fff' }}
          >
            <Mic size={22} color={isListening ? '#fff' : '#f87171'} />
          </button>

          <button
            className={`util-btn ${accessibleRoute ? 'active' : ''}`}
            onClick={() => setIsAccessibilityModalOpen(true)}
            title="Accessibilità & Strada Facile"
            style={accessibleRoute ? { background: '#2563eb', color: '#fff' } : {}}
          >
            <Accessibility size={22} color={accessibleRoute ? '#fff' : '#60a5fa'} />
          </button>

          <div className="layer-controls">
            <button
              className="util-btn"
              onClick={() => {
                const layers = museumData.layers || [];
                const idx = layers.findIndex(l => l.id === activeLayerId);
                if (idx < layers.length - 1) setActiveLayerId(layers[idx + 1].id);
              }}
              title="Floor Up"
            >
              <ChevronUp size={24} />
            </button>
            <div className="layer-indicator">
              L{museumData?.layers?.findIndex(l => l.id === activeLayerId) + 1 || 1}
            </div>
            <button
              className="util-btn"
              onClick={() => {
                const layers = museumData.layers || [];
                const idx = layers.findIndex(l => l.id === activeLayerId);
                if (idx > 0) setActiveLayerId(layers[idx - 1].id);
              }}
              title="Floor Down"
            >
              <ChevronDown size={24} />
            </button>
          </div>
        </div>

        {/* New utility buttons */}
        <div className="utility-buttons-top">
          {!isTrackingUser && (
            <button
              className="util-btn recenter-btn slide-in-top"
              onClick={() => setIsTrackingUser(true)}
              title="Recenter Camera"
            >
              <LocateFixed size={24} color="#3b82f6" />
            </button>
          )}

          <div className="zoom-controls">
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.min(prev + 0.5, 15))} title="Zoom In"><Plus size={20} /></button>
            <button className="util-btn zoom-btn" onClick={() => setMapZoom(prev => Math.max(prev - 0.5, 1))} title="Zoom Out"><Minus size={20} /></button>
          </div>

          <div className="more-menu-wrapper">
            <button
              className="util-btn"
              onClick={() => setShowMoreMenu(!showMoreMenu)}
              title="More Options"
            >
              {showMoreMenu ? <X size={24} /> : <MoreVertical size={24} />}
            </button>

            {showMoreMenu && (
              <div className="more-menu slide-in-top">
                <button className="menu-item" title="Find Toliet">
                  <ToiletIcon size={20} /> Toilet
                </button>
                <button className="menu-item" title="Find Restaurant">
                  <RestaurantIcon size={20} /> Restaurant
                </button>
              </div>
            )}
          </div>
        </div>

        {/* D-Pad Controller for manual touring */}
        <div className="dpad-controller">
          <div className="dpad-row">
            <button onPointerDown={() => startMove(0, -1)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn up"><ChevronUp size={28} /></button>
          </div>
          <div className="dpad-row middle">
            <button onPointerDown={() => startMove(-1, 0)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn left"><ChevronLeft size={28} /></button>
            <div className="dpad-center"></div>
            <button onPointerDown={() => startMove(1, 0)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn right"><ChevronRight size={28} /></button>
          </div>
          <div className="dpad-row">
            <button onPointerDown={() => startMove(0, 1)} onPointerUp={stopMove} onPointerLeave={stopMove} onContextMenu={(e) => e.preventDefault()} className="dpad-btn down"><ChevronDown size={28} /></button>
          </div>
        </div>
      </div>

      {showPopup && (
        <ItemDescription
          item={currentItem}
          onPlayPause={togglePlay}
          isPlaying={isPlaying}
          onClose={() => setShowPopup(false)}
        />
      )}


      <VoiceControlModal
        isOpen={isVoiceModalOpen}
        onClose={() => setIsVoiceModalOpen(false)}
        isListening={isListening}
        transcript={transcript}
        lastFeedback={lastFeedback}
        onStartListening={startListening}
        onStopListening={stopListening}
        onSelectCommand={executeManualCommand}
      />

      <AccessibilityModal
        isOpen={isAccessibilityModalOpen}
        onClose={() => setIsAccessibilityModalOpen(false)}
        accessibleRoute={accessibleRoute}
        onToggleAccessibleRoute={() => {
          setAccessibleRoute(prev => !prev);
          showToast(`Percorso accessibile ${!accessibleRoute ? 'ATTIVATO (senza scale)' : 'DISATTIVATO'}`);
        }}
        fontSizeMultiplier={fontSizeMultiplier}
        onChangeFontSize={setFontSizeMultiplier}
        speechRate={speechRate}
        onChangeSpeechRate={setSpeechRate}
        autoPlayAudio={autoPlayAudio}
        onToggleAutoPlayAudio={() => setAutoPlayAudio(prev => !prev)}
        highContrast={highContrast}
        onToggleHighContrast={() => setHighContrast(prev => !prev)}
      />

      <SyncSessionModal
        isOpen={isSyncModalOpen}
        onClose={() => setIsSyncModalOpen(false)}
        isTeacherMode={isTeacherMode}
        isSyncedVisitor={isSyncedVisitor}
        activeMnemonic={activeMnemonic}
        connectedVisitorsCount={connectedVisitorsCount}
        onStartTeacherSession={handleStartTeacherSession}
        onJoinVisitorSession={handleJoinVisitorSession}
        onLeaveSyncSession={handleLeaveSyncSession}
        onBroadcastState={handleBroadcastState}
        onStartGroupQuiz={handleStartGroupQuiz}
        teacherQuizResults={teacherQuizResults}
      />

      <QuizModal
        isOpen={isQuizModalOpen}
        onClose={() => setIsQuizModalOpen(false)}
        quiz={activeQuizData}
        onSubmitResults={handleSubmitQuizResults}
      />

      <BottomBar
        onPrev={handlePrev}
        onNext={handleNext}
        onPlayPause={togglePlay}
        onMic={handleMicRequest}
        onEasier={() => setIsAccessibilityModalOpen(true)}
        onSeekBack={handleSeekBack}
        onSeekForward={handleSeekForward}
        isPlaying={isPlaying}
        hasPrev={currentIndex > 0}
        hasNext={currentIndex < items.length - 1}
        progress={((currentIndex + 1) / items.length) * 100}
        showDescription={showDescription}
        setShowDescription={setShowDescription}
        currentItem={currentItem}
        fontSizeMultiplier={fontSizeMultiplier}
        highContrast={highContrast}
      />
    </div>
  );
}
